\version "2.22.0"

\include "scores/full_score.ly"

% \include "scores/clno1.ly"
% \include "scores/clno2.ly"
% \include "scores/trb1.ly"
% \include "scores/trb2.ly"
% \include "scores/vl1.ly"
% \include "scores/vl2.ly"
% \include "scores/vla1.ly"
% \include "scores/vla2.ly"
% \include "scores/coro.ly"
% \include "scores/org.ly"
% \include "scores/b.ly"
